name: Ejemplo
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop

permissions:
  contents: read
jobs:
  on_start:
    name: Eco
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Let's get all the branches.
      - run: echo "Workflow completado"