name: 'Terraform'
on:
  push:
    branches: 
      - feature/*
  pull_request: 
    branches: 
      - release/*
      - main
      - master
  workflow_dispatch:
    inputs:
      env-type:
        required: true
        type: string

jobs:
  CallerMatrix:
    strategy:
      matrix:
        env-type: [dev, pre, pro]
    uses: ./.github/workflows/terraform-called.yml
    with:
      env-type: ${{ matrix.env-type }}