on:
  push:
  workflow_dispatch:

jobs:
  CallerMatrix:
    strategy:
      matrix:
        env-type: [dev, pre, pro]
    uses: saguit03/terraform-gitflow/.github/workflows/terraform-called.yml@actions
    with:
      env-type: ${{ matrix.env-type }}