name: Terraform

on:
  push:
  workflow_dispatch:

jobs:
  prueba:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: 'dev'

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4